--- Default configuration for Taskbar.
---
--- Values in this module are copied into the Spoon instance and may be
--- overridden from the user's Hammerspoon init.lua before calling :start().

local config = {
    barHeight = 34,
    iconSize = 20,
    hoverIconGrowth = 3,
    hoverIconLift = 1,
    padding = 8,
    itemSpacing = 6,
    placement = "bottom",
    logLevel = "info",
    reserveScreenSpace = true,
    reservationDebounce = 0.12,
    pinnedApps = {},
    persistPinnedApps = true,
    contextMenu = true,
    dragReorder = true,
    dragThreshold = 5,
    separatorWidth = 1,
    separatorSpacing = 8,
    showClock = true,
    clockFormat = "%a %d %b  %H:%M",
    clockWidth = 122,
    widgetSpacing = 8,
    widgetButtonWidth = 34,
    showTrash = true,
    trashIconSize = 18,
    trashDebug = false,
    widgetRefreshInterval = 15,
    accessibilityBadges = true,
    accessibilityBadgeInterval = 2,
    accessibilityScanMaxNodes = 700,
    accessibilityScanMaxDepth = 12,
    accessibilityDebug = false,
    accessibilityDebugMaxLines = 80,
    notificationCenterObserver = true,
    notificationCenterDebug = false,
    notificationCenterEvents = { "layoutChanged", "created" },
    attentionDotSize = 12,
    attentionCounter = true,
    attentionCounterMax = 99,
    runningIndicatorWidth = 14,
    runningIndicatorHeight = 3,
    runningIndicatorRadius = 1.5,
    runningIndicatorDotSize = 4,
    runningIndicatorBottom = 3,
    debugNotificationBadge = false,
    debugNotificationBadgeCount = 3,
    debugNotificationBadgeName = "Badge Test",
    accessibilityBadgeKeywords = {
        "notification",
        "notifications",
        "unread",
        "message",
        "messages",
        "alert",
        "alerts",
    },

    colors = {
        background = { red = 0.05, green = 0.05, blue = 0.06, alpha = 0.82 },
        separator = { red = 0.52, green = 0.52, blue = 0.56, alpha = 0.55 },
        clockText = { red = 0.86, green = 0.86, blue = 0.88, alpha = 1.0 },
        trash = { red = 0.76, green = 0.78, blue = 0.82, alpha = 1.0 },
        trashFull = { red = 0.94, green = 0.94, blue = 0.96, alpha = 1.0 },
        trashFill = { red = 0.38, green = 0.58, blue = 0.96, alpha = 0.80 },
        attention = { red = 0.92, green = 0.08, blue = 0.10, alpha = 1.0 },
        attentionText = { red = 1.0, green = 1.0, blue = 1.0, alpha = 1.0 },
        runningIndicator = { red = 0.86, green = 0.88, blue = 0.92, alpha = 0.95 },
    },

    excludedApps = {
        ["com.apple.dock"] = true,
        ["com.apple.WindowManager"] = true,
        ["com.apple.controlcenter"] = true,
        ["com.apple.notificationcenterui"] = true,
        ["com.apple.SystemUIServer"] = true,
        ["org.hammerspoon.Hammerspoon"] = true,
    },
}

return config
